# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Danielle Teixeira
email: dannyserena@gmail.com
description: "Blog com conteúdo de Desenvolvimento Web e Mobile - Feito com Jekyll" # the subpath of your site, e.g. /blog
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://dannyserena.github.io" # the base hostname & protocol for your site
twitter_username: dannyserena
github_username:  dannyserena

# Build settings usado pelo GITHUB
markdown: kramdown
permalink: title

